# Generated by Django 3.0.7 on 2020-06-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tejazon', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='caste',
        ),
    ]
